### ISSUE TITLE
Unable to Read Certain sensors

### ISSUE THREAD

**Issue by cakuhn** [kellerza/sunsynk#129]
HI

I could previously read the below sensors, however now that I have migrated by Home Assistant to a new virtual machine I am unable to read them.

Basically the log file show the process is failing when I start with the following sensors:

When I remove the Time and Capacity sensors it starts up perfectly.  Is the sensors not available anymore?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2023-04-20 14:57:29,571 INFO    Loading HASS OS configuration
2023-04-20 14:57:29,587 DEBUG   could not patch umodbus: numpy not found
2023-04-20 14:57:29,592 INFO    ############################################################
2023-04-20 14:57:29,592 INFO        Sensor deprecated: total_pv_power -> total_pv_energy
2023-04-20 14:57:29,592 INFO    ############################################################
Traceback (most recent call last):
  File "/usr/src/app/./run.py", line 472, in <module>
    startup()
  File "/usr/src/app/./run.py", line 261, in startup
    setup_sensors()
  File "/usr/src/app/./run.py", line 307, in setup_sensors
    for dep in sen.dependencies:
TypeError: 'method' object is not iterable
[cmd] ./run.py exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

  - prog1_time:now
  - prog1_capacity:now
  - prog2_time:now
  - prog2_capacity:now
  - prog3_time:now
  - prog3_capacity:now
  - prog4_time:now
  - prog4_capacity:now
  - prog5_time:now
  - prog5_capacity:now
  - prog6_time:now
  - prog6_capacity:now

**Comment by kellerza** [comment]
Please use the MULTI addon only
