### ISSUE TITLE
Data reporting randomly pauses for a couple of minutes

### ISSUE THREAD

**Issue by adnovea** [kellerza/sunsynk#192]
### Issue related to

Sunsynk / pymodbus Home Assistant Add-On

### Describe the issue/bug

Data reporting pause randomly for about a quarter of an hour. I notice this issue through the inverter Date Time update.
I left the date_time entity as defined by default and copied all the sensors needed into the /share/hass-addon-sunsynk/mysensors.py file for easy debugging.

**Expected behavior**
I have setup the SCHEDULE parameters for a reporting twice a minute.
Everything works for a undetermined period of time (_half an hour to a couple of hours_) then the entities update pause for about a quarter of an hour.

### Your environment

- Home Assistant version: 2023.9.3
- Addon:
  - Name: Sunsynk/Deye Inverter Add-on (multi)
  - Version: 0.6.4
- Inverter:
  - Make: Deye
  - Model: Sun 5K SG03LP1-EU
  - Firmware: 0000-C366 / 0000-3384
- Adaptor details:
  - solarman LSE-3 (Ethernet version)

### You configuration

```
DRIVER: pymodbus
INVERTERS:
  - SERIAL_NR: "XXXXXXXX"
    HA_PREFIX: SunSynk
    MODBUS_ID: 1
    DONGLE_SERIAL_NUMBER: "21XXXXXXXXX"
    PORT: tcp://192.168.XXX.XXX:8899
SENSOR_DEFINITIONS: single-phase
SENSORS:
  - mysensors
  - date_time
SENSORS_FIRST_INVERTER: []
MANUFACTURER: Deye
READ_ALLOW_GAP: 2
READ_SENSORS_BATCH_SIZE: 24
SCHEDULES:
  - KEY: date_time
    READ_EVERY: 15
    REPORT_EVERY: 30
    CHANGE_ANY: true
  - KEY: RW
    READ_EVERY: 15
    REPORT_EVERY: 30
    CHANGE_ANY: true
  - KEY: W
    READ_EVERY: 15
    REPORT_EVERY: 30
    CHANGE_BY: 80
  - KEY: KWH
    READ_EVERY: 30
    REPORT_EVERY: 30
  - KEY: any_unit
    READ_EVERY: 30
    REPORT_EVERY: 30
  - KEY: no_unit
    READ_EVERY: 15
    REPORT_EVERY: 30
    CHANGE_ANY: true
NUMBER_ENTITY_MODE: auto
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_USERNAME: <removed>
MQTT_PASSWORD: <removed>
DEBUG: 0
DEBUG_DEVICE: /dev/ttyAMA0
```

### Logs  (P.S. Don't know where to find the complete log file)

```logs
12:25:49 INFO    sunsynk library version: 0.6.4
12:25:49 INFO    Schedules:
+-----------+-----+------+--------+-----------+----------+------------+
|    Key    | src | Read | Report | Change by | Change % | Change any |
+-----------+-----+------+--------+-----------+----------+------------+
| date_time |  *  |  15  |   30   |           |          |    True    |
|     rw    |  *  |  15  |   30   |           |          |    True    |
|     w     |  *  |  15  |   30   |     80    |          |            |
|    kwh    |  *  |  30  |   30   |           |          |            |
|  any_unit |  *  |  30  |   30   |           |          |            |
|  no_unit  |  *  |  15  |   30   |           |          |    True    |
+-----------+-----+------+--------+-----------+----------+------------+
12:25:49 INFO    Using Single phase sensor definitions.
12:25:49 INFO    Importing /share/hass-addon-sunsynk/mysensors.py...
12:25:49 INFO      custom sensors: battery_temperature, battery_voltage, battery_soc, battery_power, battery_current, battery_alarm, battery_fault, inverter_power, inverter_voltage, inverter_current, inverter_frequency, grid_frequency, grid_power, grid_ld_power, grid_l2_power, grid_voltage, grid_current, grid_ct_power, energy_selling, load_power, load_l1_power, load_l2_power, load_frequency, smartload_status, pv1_power, pv1_voltage, pv1_current, pv2_power, pv2_voltage, pv2_current, aux_power, essential_power, essential_1_power, essential_2_power, non_essential_power, day_active_energy, day_battery_charge, day_battery_discharge, day_grid_import, day_grid_export, day_load_energy, day_pv_energy, total_active_energy, total_battery_charge, total_battery_discharge, total_grid_export, total_grid_import, total_load_energy, total_pv_energy, rated_power, serial, device_type, fault, dc_transformer_temperature, radiator_temperature, grid_connected, inverter_id, board_version, comm_version, warning_message, overall_state, grid_charge_enabled, generator_input, load_limit, use_timer, priority_load, prog1_time, prog2_time, prog3_time, prog4_time, prog5_time, prog6_time, prog1_capacity, prog2_capacity, prog3_capacity, prog4_capacity, prog5_capacity, prog6_capacity, prog1_charge, prog2_charge, prog3_charge, prog4_charge, prog5_charge, prog6_charge, prog1_mode, prog2_mode, prog3_mode, prog4_mode, prog5_mode, prog6_mode
12:25:49 INFO    Added hidden sensors as other sensors depend on it: Rated power, Serial
12:25:49 INFO    Connecting to tcp://192.168..***.***:8899
12:25:49 INFO    PyModbus 3.4.1 tcp: 192.168.***.***:8899
12:25:49 INFO    Reading startup sensors Prog1 Time, Prog4 Time, Prog5 Time, Prog6 Time, Rated power, Battery Low Capacity, Prog2 Time, Serial, Prog3 Time
12:25:52 ERROR   Timeout 
12:25:54 INFO    ############################################################
12:25:54 INFO                 Inverter serial number '****3450'
12:25:54 INFO    ############################################################
12:25:54 INFO    MQTT: Connecting to mqtt-user@core-mosquitto:1883
12:25:55 INFO    MQTT: Connection successful
12:25:56 INFO    MQTT: Removing HASS MQTT discovery info homeassistant/select/22******/system_date/config
12:25:56 INFO    Read every (inverter 1)
+----+----------------------------------------------------------------------------------+
| s  |                                     Sensors                                      |
+----+----------------------------------------------------------------------------------+
| 15 |   warning_message, priority_load, device_type, smartload_status, comm_version,   |
|    |       prog1_capacity, load_limit, prog3_charge, use_timer, load_l1_power,        |
|    |         prog2_charge, prog6_mode, prog3_mode, prog4_mode, load_l2_power,         |
|    |   essential_power, grid_charge_enabled, grid_ct_power, prog6_time, prog3_time,   |
|    |      grid_connected, load_power, prog2_mode, prog4_charge, prog5_capacity,       |
|    |       prog6_charge, prog1_time, prog4_capacity, aux_power, grid_l2_power,        |
|    | essential_1_power, prog4_time, grid_power, prog1_mode, pv1_power, grid_ld_power, |
|    |      fault, prog2_capacity, board_version, prog6_capacity, energy_selling,       |
|    |        battery_low_capacity, essential_2_power, prog2_time, prog5_charge,        |
|    |       battery_fault, prog3_capacity, prog1_charge, pv2_power, prog5_time,        |
|    |      battery_alarm, battery_power, inverter_id, overall_state, prog5_mode,       |
|    |         generator_input, inverter_power, date_time, non_essential_power          |
| 30 | pv1_current, pv2_voltage, day_battery_discharge, grid_voltage, inverter_voltage, |
|    |      total_battery_discharge, pv2_current, load_frequency, day_load_energy,      |
|    |   battery_soc, inverter_current, day_grid_import, dc_transformer_temperature,    |
|    |     total_grid_export, grid_current, day_battery_charge, day_active_energy,      |
|    |   total_battery_charge, radiator_temperature, total_pv_energy, day_pv_energy,    |
|    |     total_grid_import, battery_temperature, inverter_frequency, pv1_voltage,     |
|    |    battery_current, total_active_energy, day_grid_export, total_load_energy,     |
|    |                         battery_voltage, grid_frequency                          |
+----+----------------------------------------------------------------------------------+
12:25:56 INFO    Report every (inverter 1)
+----+----------------------------------------------------------------------------------+
| s  |                                     Sensors                                      |
+----+----------------------------------------------------------------------------------+
| 30 |     comm_version, inverter_voltage, load_limit, load_frequency, pv2_current,     |
|    |   battery_soc, grid_ct_power, prog6_time, day_battery_charge, prog2_capacity,    |
|    |    grid_ld_power, fault, total_grid_import, battery_temperature, prog2_time,     |
|    |       prog1_charge, prog5_time, overall_state, battery_power, inverter_id,       |
|    | battery_voltage, date_time, prog3_time, prog3_mode, priority_load, device_type,  |
|    |   grid_voltage, total_battery_discharge, prog3_charge, use_timer, prog6_mode,    |
|    |       dc_transformer_temperature, grid_connected, load_power, prog2_mode,        |
|    |   prog4_charge, grid_current, prog4_capacity, aux_power, total_battery_charge,   |
|    |     radiator_temperature, grid_power, prog1_mode, pv1_power, battery_fault,      |
|    |    day_grid_export, total_load_energy, non_essential_power, warning_message,     |
|    | pv1_current, pv2_voltage, day_battery_discharge, prog2_charge, inverter_current, |
|    |     load_l2_power, essential_power, prog6_charge, grid_l2_power, prog4_time,     |
|    |   day_pv_energy, battery_low_capacity, essential_2_power, inverter_frequency,    |
|    |     pv1_voltage, pv2_power, battery_alarm, total_active_energy, prog5_mode,      |
|    |  smartload_status, prog1_capacity, load_l1_power, day_load_energy, prog4_mode,   |
|    |     day_grid_import, grid_charge_enabled, total_grid_export, prog5_capacity,     |
|    |        day_active_energy, prog1_time, essential_1_power, total_pv_energy,        |
|    |   board_version, prog6_capacity, energy_selling, prog5_charge, prog3_capacity,   |
|    |         battery_current, generator_input, inverter_power, grid_frequency         |
+----+----------------------------------------------------------------------------------+
18:32:18 WARNING Did not complete read, only read 0/1
07:31:19 INFO    Queue update use_timer=OFF
07:31:22 INFO    Writing sensor use_timer=OFF Registers:{248=0x00fe} [Register 255-->0]
07:31:24 ERROR   General exception: unpack requires a buffer of 4 bytes
07:31:24 ERROR   Fatal error: protocol.data_received() call failed.
protocol: <pymodbus.client.tcp.AsyncModbusTcpClient object at 0x7f89622890>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/pymodbus/transport/transport.py", line 289, in data_received
    self.datagram_received(data, None)
  File "/usr/local/lib/python3.11/site-packages/pymodbus/transport/transport.py", line 303, in datagram_received
    cut = self.callback_data(self.recv_buffer, addr=addr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/base.py", line 219, in callback_data
    self.framer.processIncomingPacket(data, self._handle_response, slave=0)
  File "/usr/local/lib/python3.11/site-packages/pymodbus/framer/base.py", line 137, in processIncomingPacket
    self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/pymodbus/framer/socket_framer.py", line 147, in frameProcessIncomingPacket
    self._process(callback, tid)
  File "/usr/local/lib/python3.11/site-packages/pymodbus/framer/socket_framer.py", line 154, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
07:31:24 ERROR   ConnectionException in read_sunsynk: Modbus Error: [Connection] Connection lost during request

```

Thanks for this very complete add-on and for your help to tackle this issue.

**Comment by kellerza** [comment]
Could probably try to suppress that error, but its likely the dongle disconnected for some reason

Today the retry mechanism should be a restart of the app with the addon’s watchdog

**Comment by adnovea** [comment]
Dear Johann,
Thanks for your quick reply and for the excellent work you achieved 🥇 
I know how much effort it takes to maintain open-source devs!

Unfortunately, I cannot consider the dongle disconnection as the root cause of my problem because I ran the [Stephan Joubert](https://github.com/StephanJoubert/home_assistant_solarman)'s Solarman Integration for a couple of months without issues using my LSE-3 dongle (_but Stephan's integration has no inverter control possibilities_).

I tried to tackle the issue but I miss some pieces of information such as :
- Where could the full log file be found (_only tail is displayed on the log page_)
- Where is the Add-ons installed (_could I access the files using HA's Terminal_ ?)

I also suspected the Mosquitto broker to be responsible, but using MQTT Explorer I have abandoned this possibility for the time being. Moreover, I have an other add-on using MQTT without issues.

The snapshots below shows random long pause (15 mins) over the data reading.
It very clear on the 2nd picture that shows the date_time updates. The 4 pauses seems to be somewhat periodic !

I have removed my "custom sensors" and changed my Schedule  to :
```
SCHEDULES:
  - KEY: date_time
    READ_EVERY: 30
    REPORT_EVERY: 30
    CHANGE_ANY: true
  - KEY: RW
    READ_EVERY: 30
    REPORT_EVERY: 30
    CHANGE_ANY: true
  - KEY: W
    READ_EVERY: 30
    REPORT_EVERY: 30
    CHANGE_BY: 80
  - KEY: KWH
    READ_EVERY: 30
    REPORT_EVERY: 30
  - KEY: any_unit
    READ_EVERY: 30
    REPORT_EVERY: 30
  - KEY: no_unit
    READ_EVERY: 30
    REPORT_EVERY: 30
    CHANGE_ANY: true
```
Thanks for your help

![image](https://github.com/kellerza/sunsynk/assets/44359861/3dd9f932-197b-49c6-843a-b4f431882019)

![pause2 jog](https://github.com/kellerza/sunsynk/assets/44359861/5191b77d-b737-46d2-9af3-6bd8a4ac05b9)

**Comment by kellerza** [comment]
At some point I added some improvements to the dev version of the addon & you could try using that for a while?

**Comment by adnovea** [comment]
Thanks Johann for your reply.
I tried the beta version with no success. I cannot understand why the add-on pauses so long making the data unusable.
I had to fallback to Stephen's add-on to get relevant data records.
I hope this problem will be solved. However,I have no idea for the time being.

**Comment by purcell-lab** [comment]
Similar issue here:

![image](https://github.com/kellerza/sunsynk/assets/79175134/6e4335aa-fa06-4880-9ce6-87823abc7d48)

I have an hourly automation to restart, but would like to use a better trigger.
![Screenshot_20240310-073551](https://github.com/kellerza/sunsynk/assets/79175134/02679590-919b-4559-9ce7-e9ca8038f863)

**Comment by kellerza** [comment]
Only noticed now you are using the pymodbus driver, while trying to connect to the solarman dongle.
Please use the solarman driver

```yaml
DRIVER: pymodbus
INVERTERS:
  - SERIAL_NR: "XXXXXXXX"
    HA_PREFIX: SunSynk
    MODBUS_ID: 1
    DONGLE_SERIAL_NUMBER: "21XXXXXXXXX"
    PORT: tcp://192.168.XXX.XXX:8899
```
