### ISSUE TITLE
Unknown register value 512

### ISSUE THREAD

**Issue by deondti** [kellerza/sunsynk#361]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

When i run Solarman it runs perfect.
Pymodbus not working on my 16Kw DEYE
""WARNING device_type: Unknown register value 512. Consider extending the definition with a PR. https://github.com/kellerza/sunsynk/tree/main/src/sunsynk/definitions""
and
""ERROR   (12 in 5 min) OSError in callback read_ss: timeout reading 1 registers from 603; timeout reading 1 registers from 611 poll_need_to_read""
are the errors I receive in the log, no posting to MQTT, MQTT is connected, the only change is the solarman/pymodbus connection.

**Expected behavior**
No Errors, posting to MQTT

### Your environment

- Home Assistant version: 2023.8.x
- Addon:
  - Name: sunsynk-multi
  - Version:  0.7.5 , latest
- Inverter:
  - Make: DEYE
  - Model: 16Kw
  - Firmware: main; 9025-1726 , protocol V0.2.0.1
- Adaptor details:
  - RS485/RS232/solarman
  - RS485/RS232 ftdi

### You configuration

```yaml
DRIVER: pymodbus
INVERTERS:
  - SERIAL_NR: "2404180592"
    HA_PREFIX: SS
    MODBUS_ID: 1
    DONGLE SERIAL NUMBER: "0"
    PORT: /dev/ttyUSB0
SENSOR_DEFINITIONS: single-phase
SENSORS:
  - energy_management
  - power_flow_card
  - pv2_power
  - pv3_power
  - all
  - battery_soc
SENSORS_FIRST_INVERTER:
  - settings
MANUFACTURER: Deye
READ_ALLOW_GAP: 2
READ_SENSORS_BATCH_SIZE: 20
SCHEDULES:
  - KEY: W
    READ_EVERY: 5
    REPORT_EVERY: 60
    CHANGE_ANY: false
    CHANGE_BY: 80
    CHANGE_PERCENT: 0
NUMBER_ENTITY_MODE: auto
PROG_TIME_INTERVAL: 15
MQTT_HOST: 192.168.20.22
MQTT_PORT: 1884
MQTT_USERNAME: ICM
MQTT_PASSWORD: ICM123456
DEBUG_DEVICE: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0


```

### Logs

```logs
s6-rc: info: service legacy-services: stopping
[12:50:04] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sunsynk (no readiness notification)
s6-rc: info: service legacy-services successfully started
12:50:13 INFO    Loading config: /data/options.json
12:50:13 INFO    sunsynk library version: 0.6.5
12:50:14 INFO    Schedules:
+-----------+-----+------+--------+-----------+----------+------------+
|    Key    | src | Read | Report | Change by | Change % | Change any |
+-----------+-----+------+--------+-----------+----------+------------+
| date_time |     |  60  |   60   |           |          |    True    |
|     rw    |     |  5   |  300   |           |          |    True    |
|    enum   |     |  5   |  300   |           |          |    True    |
|     w     |  *  |  5   |   60   |    80.0   |          |            |
|    kwh    |     | 300  |  300   |           |          |            |
|  any_unit |     |  15  |  300   |           |          |            |
|  no_unit  |     |  15  |  300   |           |          |    True    |
+-----------+-----+------+--------+-----------+----------+------------+
12:50:14 INFO    Using Single phase sensor definitions.
12:50:14 INFO    Importing /share/hass-addon-sunsynk/mysensors.py...
12:50:14 INFO      custom sensors: pv3_power, pv3_voltage, pv3_current, l1_load_current
12:50:14 INFO    Added hidden sensors as other sensors depend on it: Rated power, Serial
12:50:14 INFO    Connecting to /dev/ttyUSB0
12:50:14 INFO    PyModbus 3.7.2 Serial: /dev/ttyUSB0
12:50:14 INFO    Reading startup sensors Rated power, Prog3 Time, Battery Shutdown Capacity, Battery Low Capacity, Prog4 Time, Battery Shutdown voltage, Prog2 Time, Battery Low voltage, Prog6 Time, Serial, Prog1 Time, Battery Float voltage, Prog5 Time
12:50:17 INFO    ############################################################
12:50:17 INFO                 Inverter serial number '****0592'
12:50:17 INFO    ############################################################
12:50:17 INFO    MQTT: Connecting to ICM@192.168.20.22:1884
12:50:18 INFO    MQTT: Connection successful
12:50:19 INFO    Read every (inverter 1)
+-----+---------------------------------------------------------------------------------+
|  s  |                                     Sensors                                     |
+-----+---------------------------------------------------------------------------------+
|  5  |     prog1_mode, battery_absorption_voltage, battery_low_voltage, prog4_time,    |
|     |       prog5_charge, pv3_power, inverter_power, battery_max_charge_current,      |
|     | load_l2_power, battery_float_voltage, prog5_capacity, prog4_charge, prog5_mode, |
|     |  prog5_time, prog3_charge, prog6_charge, prog3_mode, prog6_mode, battery_power, |
|     |  grid_charge_enabled, essential_2_power, grid_ct_power, prog2_time, load_limit, |
|     |       grid_l2_power, essential_power, battery_restart_capacity, aux_power,      |
|     |       prog6_power, prog3_voltage, prog5_voltage, prog1_power, prog1_time,       |
|     |       prog2_capacity, prog1_charge, grid_power, prog2_mode, prog6_voltage,      |
|     |  generator_input, prog3_time, battery_shutdown_capacity, battery_low_capacity,  |
|     |        prog5_power, pv2_power, battery_shutdown_voltage, prog3_capacity,        |
|     |       grid_charge_battery_current, device_type, prog6_time, load_l1_power,      |
|     |      prog4_power, prog4_voltage, prog3_power, prog2_power, prog6_capacity,      |
|     |         essential_1_power, solar_export, max_solar_power, prog1_voltage,        |
|     |         non_essential_power, prog4_mode, prog1_capacity, max_sell_power,        |
|     |    battery_equalization_voltage, prog2_charge, battery_max_discharge_current,   |
|     |        grid_ld_power, priority_load, use_timer, battery_restart_voltage,        |
|     |               prog4_capacity, load_power, prog2_voltage, pv1_power              |
|  15 |    pv1_current, battery_temperature, overall_state, environment_temperature,    |
|     |   grid_frequency, battery_discharge_limit_current, battery_soc, control_mode,   |
|     |   load_frequency, day_reactive_energy, bat1_soc, l1_load_current, pv3_current,  |
|     |     grid_voltage, sd_status, grid_connected, bat1_cycle, fault, pv2_voltage,    |
|     |          pv2_current, pv3_voltage, inverter_frequency, battery_voltage,         |
|     |  battery_charge_limit_current, battery_current, inverter_current, pv1_voltage,  |
|     | battery_charging_voltage, grid_current, inverter_voltage, radiator_temperature, |
|     |                            dc_transformer_temperature                           |
|  60 |                                    date_time                                    |
| 300 |    month_grid_energy, day_grid_export, total_active_energy, day_grid_import,    |
|     |    day_load_energy, total_grid_import, total_load_energy, day_active_energy,    |
|     |  month_load_energy, day_battery_discharge, total_grid_export, year_load_energy, |
|     |      total_battery_charge, year_grid_export, day_pv_energy, year_pv_energy,     |
|     |  total_battery_discharge, day_battery_charge, month_pv_energy, total_pv_energy  |
+-----+---------------------------------------------------------------------------------+
12:50:19 INFO    Report every (inverter 1)
+-----+----------------------------------------------------------------------------------+
|  s  |                                     Sensors                                      |
+-----+----------------------------------------------------------------------------------+
|  60 |    essential_1_power, battery_power, non_essential_power, essential_2_power,     |
|     |       grid_ct_power, pv2_power, pv3_power, inverter_power, grid_l2_power,        |
|     |     essential_power, grid_ld_power, aux_power, load_l2_power, load_l1_power,     |
|     |                   date_time, load_power, pv1_power, grid_power                   |
| 300 |   prog1_mode, battery_absorption_voltage, prog4_time, environment_temperature,   |
|     |            prog5_charge, grid_frequency, battery_max_charge_current,             |
|     | battery_discharge_limit_current, prog4_charge, prog3_charge, day_active_energy,  |
|     |   month_load_energy, total_grid_export, load_limit, battery_restart_capacity,    |
|     |  grid_connected, fault, prog5_voltage, prog6_voltage, pv2_voltage, prog5_power,  |
|     |    battery_voltage, grid_charge_battery_current, day_pv_energy, prog3_power,     |
|     |    prog1_voltage, day_battery_charge, prog2_charge, priority_load, use_timer,    |
|     |   dc_transformer_temperature, pv1_current, pv3_current, day_battery_discharge,   |
|     |   prog2_time, sd_status, prog6_power, prog3_voltage, prog1_charge, prog1_time,   |
|     |    prog2_capacity, prog2_mode, inverter_frequency, battery_shutdown_capacity,    |
|     |  battery_low_capacity, device_type, prog6_time, solar_export, max_solar_power,   |
|     |       max_sell_power, pv1_voltage, battery_charging_voltage, grid_current,       |
|     |    prog2_voltage, radiator_temperature, year_pv_energy, battery_temperature,     |
|     | overall_state, month_grid_energy, day_grid_export, control_mode, prog5_capacity, |
|     |       total_active_energy, day_reactive_energy, prog6_charge, prog3_mode,        |
|     |   total_load_energy, total_grid_import, l1_load_current, grid_charge_enabled,    |
|     |          grid_voltage, year_load_energy, generator_input, pv3_voltage,           |
|     |     total_battery_charge, prog3_time, prog2_power, total_battery_discharge,      |
|     |         inverter_current, battery_equalization_voltage, month_pv_energy,         |
|     |   inverter_voltage, battery_low_voltage, battery_soc, prog5_mode, prog5_time,    |
|     |     load_frequency, bat1_soc, day_grid_import, prog6_mode, day_load_energy,      |
|     |             bat1_cycle, prog1_power, pv2_current, year_grid_export,              |
|     |      battery_shutdown_voltage, prog3_capacity, prog4_power, prog4_voltage,       |
|     |    prog6_capacity, battery_charge_limit_current, prog4_mode, prog1_capacity,     |
|     |     battery_current, battery_max_discharge_current, battery_restart_voltage,     |
|     |              prog4_capacity, battery_float_voltage, total_pv_energy              |
+-----+----------------------------------------------------------------------------------+
12:50:43 WARNING device_type: Unknown register value 512. Consider extending the definition with a PR. https://github.com/kellerza/sunsynk/tree/main/src/sunsynk/definitions
12:50:43 ERROR   OSError in callback read_ss: timeout reading 1 registers from 603; timeout reading 1 registers from 611 poll_need_to_read

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/timer_callback.py", line 81, in wrap_callback
    await cb_call

  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/sensor_callback.py", line 110, in callback_sensor
    await ist.read_sensors(

  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/a_inverter.py", line 54, in read_sensors
    await self.inv.read_sensors(sensors)

  File "/usr/local/lib/python3.11/site-packages/sunsynk/sunsynk.py", line 134, in read_sensors
    raise IOError("; ".join(errs))

OSError: timeout reading 1 registers from 603; timeout reading 1 registers from 611 poll_need_to_read

```

**Comment by kellerza** [comment]
Remove sensor all. Use less sensors

**Comment by deondti** [comment]
It was exactly that, no more errors and it's pushing to mqtt.

I will add my sensors.

Thank you
